<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'lomba_id' => 1,
                'pengusul_id' => 1,
                'nama_lomba' => 'Lomba Web Development Nasional',
                'tingkat_lomba_id' => 5,
                'deskripsi_lomba' => 'Kompetisi pengembangan website tingkat nasional untuk mahasiswa.',
                'penyelenggara_lomba' => 'Kemenkominfo',
                'jenis_penyelenggara_lomba' => 'Institusi',
                'awal_registrasi_lomba' => Carbon::parse('2025-06-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-06-30'),
                'link_pendaftaran_lomba' => 'https://contoh-lomba.com/daftar',
                'img_lomba' => 'webdev2025.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 2,
                'pengusul_id' => 22,
                'nama_lomba' => 'WS ASEAN 2025',
                'tingkat_lomba_id' => 5,
                'deskripsi_lomba' => 'WS ASEAN 2025 di bidang Cyber Security untuk Pelajar dan Mahasiswa.',
                'penyelenggara_lomba' => 'Indonesia Cyber Skills (ICS)',
                'jenis_penyelenggara_lomba' => 'Komunitas',
                'awal_registrasi_lomba' => Carbon::parse('2025-02-21'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-06-30'),
                'link_pendaftaran_lomba' => 'https://contoh-lomba.com/daftar',
                'img_lomba' => 'WSASEAN2025.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 3,
                'pengusul_id' => 1,
                'nama_lomba' => 'Hackathon AI Internasional',
                'tingkat_lomba_id' => 1,
                'deskripsi_lomba' => 'Ajang hackathon dengan tema kecerdasan buatan tingkat internasional.',
                'penyelenggara_lomba' => 'TechWorld Foundation',
                'jenis_penyelenggara_lomba' => 'Komunitas',
                'awal_registrasi_lomba' => Carbon::parse('2025-07-10'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-08-20'),
                'link_pendaftaran_lomba' => 'https://hackaiworld.org/register',
                'img_lomba' => 'hackathon_ai.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Online',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 4,
                'pengusul_id' => 1,
                'nama_lomba' => 'Kontes Mobile App Development Universitas Indonesia',
                'tingkat_lomba_id' => 6,
                'deskripsi_lomba' => 'Kompetisi pengembangan aplikasi mobile tingkat universitas.',
                'penyelenggara_lomba' => 'Universitas Indonesia',
                'jenis_penyelenggara_lomba' => 'Kampus',
                'awal_registrasi_lomba' => Carbon::parse('2025-10-15'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-11-15'),
                'link_pendaftaran_lomba' => 'https://ui-appcontest.id/daftar',
                'img_lomba' => 'mobileapp_ui.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 5,
                'pengusul_id' => 1,
                'nama_lomba' => 'Lomba Esai Bahasa Inggris Tingkat Kabupaten',
                'tingkat_lomba_id' => 4,
                'deskripsi_lomba' => 'Kompetisi esai dalam bahasa Inggris tingkat kabupaten.',
                'penyelenggara_lomba' => 'Dinas Pendidikan Kabupaten Sukabumi',
                'jenis_penyelenggara_lomba' => 'Institusi',
                'awal_registrasi_lomba' => Carbon::parse('2025-11-20'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-12-10'),
                'link_pendaftaran_lomba' => 'https://disdik-sukabumi.esai',
                'img_lomba' => 'esai_bahasa.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Offline Luar Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 6,
                'pengusul_id' => 1,
                'nama_lomba' => 'Kontes Game Indie Nasional',
                'tingkat_lomba_id' => 2,
                'deskripsi_lomba' => 'Lomba membuat game indie tingkat nasional untuk developer muda.',
                'penyelenggara_lomba' => 'IDGA (Indonesian Game Association)',
                'jenis_penyelenggara_lomba' => 'Komunitas',
                'awal_registrasi_lomba' => Carbon::parse('2026-01-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2026-02-28'),
                'link_pendaftaran_lomba' => 'https://idga-gamecontest.id',
                'img_lomba' => 'game_indie_nasional.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Online',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 7,
                'pengusul_id' => 1,
                'nama_lomba' => 'Olimpiade Algoritma Tingkat Kota',
                'tingkat_lomba_id' => 5,
                'deskripsi_lomba' => 'Olimpiade pemrograman algoritmik tingkat kota untuk siswa SMA.',
                'penyelenggara_lomba' => 'SMA Negeri 1 Yogyakarta',
                'jenis_penyelenggara_lomba' => 'Kampus',
                'awal_registrasi_lomba' => Carbon::parse('2026-02-10'),
                'akhir_registrasi_lomba' => Carbon::parse('2026-03-10'),
                'link_pendaftaran_lomba' => 'https://sman1jogja-algo.id',
                'img_lomba' => 'olim_algoritma.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 8,
                'pengusul_id' => 1,
                'nama_lomba' => 'Kompetisi UI/UX Mahasiswa Se-Jawa',
                'tingkat_lomba_id' => 2,
                'deskripsi_lomba' => 'Kompetisi desain UI/UX untuk mahasiswa di pulau Jawa.',
                'penyelenggara_lomba' => 'Asosiasi Desainer Digital Indonesia',
                'jenis_penyelenggara_lomba' => 'Komunitas',
                'awal_registrasi_lomba' => Carbon::parse('2026-03-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2026-03-31'),
                'link_pendaftaran_lomba' => 'https://addi-uiux.id',
                'img_lomba' => 'uiux_mhs_jawa.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Hybrid',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 9,
                'pengusul_id' => 1,
                'nama_lomba' => 'Lomba Bisnis Startup Tingkat Nasional',
                'tingkat_lomba_id' => 2,
                'deskripsi_lomba' => 'Kompetisi bisnis startup teknologi tingkat nasional.',
                'penyelenggara_lomba' => 'Bappenas RI',
                'jenis_penyelenggara_lomba' => 'Institusi',
                'awal_registrasi_lomba' => Carbon::parse('2026-04-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2026-04-30'),
                'link_pendaftaran_lomba' => 'https://startupbisnisnasional.id',
                'img_lomba' => 'startup_bisnis.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Offline Luar Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 10,
                'pengusul_id' => 1,
                'nama_lomba' => 'Cybersecurity Challenge Provinsi Jawa Timur',
                'tingkat_lomba_id' => 3,
                'deskripsi_lomba' => 'Kompetisi keamanan siber tingkat provinsi Jawa Timur untuk pelajar dan mahasiswa.',
                'penyelenggara_lomba' => 'Politeknik Negeri Bandung',
                'jenis_penyelenggara_lomba' => 'Kampus',
                'awal_registrasi_lomba' => Carbon::parse('2025-09-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-09-30'),
                'link_pendaftaran_lomba' => 'https://pnb-cybersec.id/register',
                'img_lomba' => 'cybersec_jabar.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Hybrid',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif',
            ],
            [
                'lomba_id' => 11,
                'pengusul_id' => 1,
                'nama_lomba' => 'IOT CHALLENGE',
                'tingkat_lomba_id' => 5,
                'deskripsi_lomba' => 'Smart Solution IoT Competition',
                'penyelenggara_lomba' => 'Politeknik Elektronika Negeri Surabaya',
                'jenis_penyelenggara_lomba' => 'Kampus',
                'awal_registrasi_lomba' => Carbon::parse('2025-02-21'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-06-30'),
                'link_pendaftaran_lomba' => 'https://contoh-lomba.com/daftar',
                'img_lomba' => 'IoTChallenge2025.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Menunggu',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 12,
                'pengusul_id' => 22,
                'nama_lomba' => 'Lomba Mobile App Development Jawa Timur #21',
                'tingkat_lomba_id' => 4,
                'deskripsi_lomba' => 'Kompetisi pengembangan aplikasi mobile tingkat provinsi untuk mahasiswa seluruh Jawa Timur 2025.',
                'penyelenggara_lomba' => 'Kemenkominfo Jawa Timur',
                'jenis_penyelenggara_lomba' => 'Institusi',
                'awal_registrasi_lomba' => Carbon::parse('2025-02-21'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-06-30'),
                'link_pendaftaran_lomba' => 'https://contoh-lomba.com/daftar',
                'img_lomba' => 'MobileApp2025.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Ditolak',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 13,
                'pengusul_id' => 6,
                'nama_lomba' => 'Lomba Game Development Jawa Timur #21',
                'tingkat_lomba_id' => 4,
                'deskripsi_lomba' => 'Kompetisi pengembangan game tingkat provinsi untuk mahasiswa seluruh Jawa Timur 2025.',
                'penyelenggara_lomba' => 'Politeknik Negeri Malang',
                'jenis_penyelenggara_lomba' => 'Kampus',
                'awal_registrasi_lomba' => Carbon::parse('2025-03-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-07-15'),
                'link_pendaftaran_lomba' => 'https://contoh-lomba.com/daftar',
                'img_lomba' => 'GameDev2025.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Ditolak',
                'status_lomba' => 'Aktif'
            ],

            // Lomba sudah selesai untuk prestasi
            [
                'lomba_id' => 14,
                'pengusul_id' => 7,
                'nama_lomba' => 'Lomba Desain Poster Kreatif',
                'tingkat_lomba_id' => 4,
                'deskripsi_lomba' => 'Kompetisi desain poster untuk pelajar tingkat SMA se-Jawa Timur.',
                'penyelenggara_lomba' => 'Dinas Kebudayaan Jawa Timur',
                'jenis_penyelenggara_lomba' => 'Institusi',
                'awal_registrasi_lomba' => Carbon::parse('2024-11-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-01-15'),
                'link_pendaftaran_lomba' => 'https://kreatif-poster.id/daftar',
                'img_lomba' => 'poster_kreatif.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Offline Dalam Kota',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 15,
                'pengusul_id' => 8,
                'nama_lomba' => 'Kompetisi Fotografi Alam Nasional',
                'tingkat_lomba_id' => 5,
                'deskripsi_lomba' => 'Lomba fotografi dengan fokus pada keindahan alam Indonesia.',
                'penyelenggara_lomba' => 'Komunitas Fotografi Indonesia',
                'jenis_penyelenggara_lomba' => 'Komunitas',
                'awal_registrasi_lomba' => Carbon::parse('2024-12-01'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-01-25'),
                'link_pendaftaran_lomba' => 'https://fotografi-alam.id/register',
                'img_lomba' => 'fotografi_alam.png',
                'tipe_lomba' => 'Individu',
                'lokasi_lomba' => 'Online',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 16,
                'pengusul_id' => 9,
                'nama_lomba' => 'Turnamen Catur Cepat Pelajar',
                'tingkat_lomba_id' => 2,
                'deskripsi_lomba' => 'Turnamen catur cepat untuk pelajar tingkat kota.',
                'penyelenggara_lomba' => 'Persatuan Catur Indonesia',
                'jenis_penyelenggara_lomba' => 'Komunitas',
                'awal_registrasi_lomba' => Carbon::parse('2025-05-20'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-05-15'),
                'link_pendaftaran_lomba' => 'https://pcatur-indonesia.id/register',
                'img_lomba' => 'turnamen_catur.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Hybrid',
                'biaya_lomba' => 'Tanpa Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif'
            ],
            [
                'lomba_id' => 17,
                'pengusul_id' => 10,
                'nama_lomba' => 'Festival Tari Tradisional Jawa',
                'tingkat_lomba_id' => 5,
                'deskripsi_lomba' => 'Festival tari tradisional untuk pelajar dan mahasiswa se-Jawa.',
                'penyelenggara_lomba' => 'Sanggar Tari Nusantara',
                'jenis_penyelenggara_lomba' => 'Kampus',
                'awal_registrasi_lomba' => Carbon::parse('2024-09-15'),
                'akhir_registrasi_lomba' => Carbon::parse('2025-01-05'),
                'link_pendaftaran_lomba' => 'https://tari-nusantara.id/daftar',
                'img_lomba' => 'festival_tari.png',
                'tipe_lomba' => 'Tim',
                'lokasi_lomba' => 'Offline Luar Kota',
                'biaya_lomba' => 'Dengan Biaya',
                'status_verifikasi' => 'Terverifikasi',
                'status_lomba' => 'Aktif'
            ],
        ];
        DB::table('t_lomba')->insert($data);
    }
}
