<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $names = [
            'ACHMAD MAULANA HAMZAH',
            'ALVANZA SAPUTRA YUDHA',
            'ANYA CALLISSTA CHRISWANTARI',
            'BERYL FUNKY MUBAROK',
            'CANDRA AHMAD DANI',
            'CINDY LAILI LARASATI',
            'DIKA ARIE ARRIFKY',
            'FAHMI YAHYA',
            'GILANG PURNOMO',
            'GWIDO PUTRA WIJAYA',
            'HIDAYAT WIDI SAPUTRA',
            'ILHAM FATURACHMAN',
            'INNAMA MAESA PUTRI',
            'JIHA RAMDHAN',
            'LELYTA MEYDA AYU BUDIYANTI',
            'M. FATIH AL GHIFARY',
            'M. FIRMANSYAH',
            'MOCH. ALFIN BURHANUDIN ALQODRI',
            'MUHAMAD SYAIFULLAH',
            'MUHAMMAD NUR AZIZ',
            'NAJWA ALYA NURIZZAH',
            'NECHA SYIFA SYAFITRI',
            'NOKLENT FARDIAN ERIX',
            'OCTRIAN ADILUHUNG TITO PUTRA',
            'SATRIO AHMAD RAMADHANI',
            'SESY TANA LINA RAHMATIN',
            'TAUFIK DIMAS EDYSTARA',
            'VINCENTIUS LEONANDA PRABOWO',
            'YANUAR RIZKI AMINUDIN',
            'ABDILLAH NOER SAID',
            'AFRIZAL QURRATUL FAIZIN',
            'AHMAD RIFQI HENDRIANSYAH',
            'ANGGA BAYU SETIAWAN',
            'ARYAN SAPUTRA RAHMAD',
            'ARYO ADI PUTRO',
            'ASLAM ROSUL AHMAD',
            'AZZAHRA ATTAQINA',
            'DAMAR GALIH FITRIANTO',
            'DEDY BAYU SETIAWAN',
            'EKYA MUHAMMAD HASFI FADLILURRAHMAN',
            'ERICHA RIZKI WARDANI',
            'FANDY WAHYU HANZURA',
            'GABRIEL BATAVIA XAVERIUS',
            'HANIF FAISHAL HILMI',
            'MICHELLE DORANI SHIBA',
            'MOHAMMAD ROIHAN AL FAHMI HIDAYATULLOH',
            'MUHAMMAD NASIH',
            'NUR AYU LAILATUL AZIZAH',
            'RAFIQO ADIB DESTARACHMAD',
            'RAMADHANI BI HAYYIN',
            'RANGGA PUTRA SYANANDA BUDHI',
            'RAUDHIL FIRDAUS NAUFAL',
            'RIZQI FAUZAN',
            'SADIYA MARITZA',
            'SAFIRO ALFARISI HARAYA',
            'SALSABILA MAHDA RUNISHA',
            'VALENTINA SANTI GREHASTA',
            'ZILAN ZALILAN',
            'ACHMAD ANFASA RABBANY',
            'AHMAD RAMADHAN BAIAKBAR',
            'AQSA HERRY PRASTYO',
            'ATABIK MUTAWAKILALALLAH',
            'AUSTRRIECH ARGONO',
            'DANDI AZRUL SYAHPUTRA',
            'DHANISA PUTRI MASHILFA',
            'DHIYA\' ULHAQ ULAYYA',
            'FABIAN ANANDA MERDANA',
            'FAUZIE IKHLASUL AMNUR',
            'GHERIYA RAHIMA JAUHAR',
            'GIOVANO ALKANDRI',
            'INDIRA NAFA AURAH HUDA',
            'KEY FIRDAUSI ALFAREL',
            'MOHAMMAD ADRI FAVIAN',
            'MUCH. ZANNUR NADHIF',
            'MUHAMMAD AMMAR HAFIZH',
            'MUHAMMAD KHALID ATTHORIQ',
            'MUHAMMAD RIFQI RIZQULLAH',
            'NAHDIA PUTRI SAFIRA',
            'PRAMUDYA SURYA ANGGARA PUTRA',
            'RANGGA DWI SAPUTRA',
            'RENDHA PUTRA RAHMADYA',
            'RIZQI BAGUS ANDREAN',
            'ROMY MAHARDIKA PANGESTU LAZUARDI',
            'SATRIA WIGUNA',
            'SATRIYO BAGUS SUSIANTO',
            'TIARA MERA SIFA',
            'TORA DIGDA KRISTIAWAN',
            'ABDULLAH SHAMIL BASAYEV',
            'ALVIN ADITIYA',
            'ANANDA SATRIA PUTRA NUGRAHA',
            'ANNISA EKA PUSPITA',
            'ASHRUL RIFKI ARDIYHASA',
            'DIMAS ADI BAYU SAMUDRA',
            'DIO ANDIKA PRADANA MULIA TAMA',
            'DWI AHMAD KHAIRY',
            'ERIK RIDHO FIRMANSYAH',
            'FIRDAUS YULI DARMAWAN',
            'GHETSA RAMADHANI RISKA ARRYANTI',
            'MOCHAMMAD FIRMANDIKA JATI KUSUMA',
            'MUHAMMAD AFIF AL GHIFARI',
            'MUHAMMAD DIMAS AJIE NUGROHO',
            'MUHAMMAD FAHREZA ROHMANSYAH',
            'MUHAMMAD FARREL CAESARIAN',
            'MUHAMMAD RIFDA MUSYAFFA\'',
            'NAKITA GAYUH CAKRAWALA',
            'OLTHA ROSYEDA AL\'HAQ',
            'PETRUS TYANG AGUNG ROSARIO',
            'RAFI ODY PRASETYO',
            'REIKA AMALIA SYAHPUTRI',
            'RIZKYA SALSABILA',
            'ROCKY ALESSANDRO KRISTANTO',
            'SATRIA ERSA NARENDRA',
            'TYARA KUSUMA NEVADA',
            'VANESSA CRISTIN NATALIA',
            'YAN DAFFA PUTRA LIANDHIE',
            'YEFTA OCTAVIANUS SANTO',
            "AGUNG FRADIANSYAH",
            "AHMAD DZUL FADHLI HANNAN",
            "AHMAD NAUFAL WASKITO AJI",
            "ANNISA KURNIAWATI",
            "ATTHALARIC NERO. M",
            "CHIKO ABILLA BASYA",
            "CINDY NUR KHOIRIYAH",
            "DIRHAMAWAN PUTRANTO",
            "ESA PRATAMA PUTRI",
            "EVAN PARISYA ADRIEL",
            "FARHAN MAWALUDIN",
            "FARREL MUCHAMMAD KAFIE",
            "FEBRIAN PERDANA",
            "FEBRIANSYAH ADI NUGROHO",
            "FIKRI MUHAMMAD ABDILLAH",
            "HIZKIA ELSADANTA",
            "LEON SHAN YOEDHA ADJIE",
            "LUTHFI TRIASWANGGA",
            "MUHAMMAD ALIF FEBRIANSYAH",
            "MUHAMMAD ZAKI",
            "NOVA ELIZA MAHARANI",
            "RAFA FADIL ARAS",
            "RAHMAD DWI FERDYAN",
            "RAKAI SETO SEMBODO",
            "RASENDRIYA DAFA SETIADI",
            "RENSI MEILA YULVINATA",
            "RIO TRI PRAYOGO",
            "SIRFARATIH",
            "VEMAS BAGUS FERMANDA",
            "AAISYAH NURSALSABIIL NI PATRIARTI",
            "ABDILLAH AGIL ARBIANSYAH",
            "ADANI SALSABILA",
            "AFIFAH KHOIRUNNISA",
            "ARIL IBBET ARDANA PUTRA",
            "CAKRA WANGSA MAY AHMAD WIDODO",
            "DEWITA ANGGRAINI",
            "DIANA RAHMAWATI",
            "FABIAN HASBILLAH OGYA-CETTA",
            "FAJAR ADITYA NUGRAHA",
            "FARREL AUGUSTA DINATA",
            "GALUNG ERLYAN TAMA",
            "GHOFFAR ABDUL JA'FAR",
            "KAMILA HABIBA PUTRI ANANTA",
            "KIBAR MUSTOFA",
            "MUCHAMMAD ARIEYA CANDRA PANGESTU",
            "MUHAMMAD IRSYAD DIMAS ABDILLAH",
            "MUHAMMAD RAFI RAJENDRA",
            "MUHAMMAD SYAHRUL GUNAWAN",
            "NADITYA PRASTIA ANDINO",
            "RIOVALDO ALFIYAN FAHMI RAHMAN",
            "RIZAL ABRAR FAHMI",
            "ROY WIJAYA",
            "SOULTAN MOHAMMAD AGNAR BISYARAH",
            "STEVAN ZAKY SETYANTO",
            "TEXTONA ARDHA RILIANTA",
            "TIONUSA CATUR PAMUNGKAS",
            "TRI SUKMA SARAH",
            "VARIZKY NALDIBA RIMRA",
            "VIDI JOSHUBZKY SAVIOLA",
            "ABDUL AZIZ",
            "ABDUL LATIF MUKHLISIN",
            "ACHMAD DIAZ HIKMAL BAIHAQI",
            "ADINDA MIRZA DEVANI",
            "ADNAN ARJU MAULANA PASHA",
            "AHMAD NAUFAL ILHAM",
            "AIDA RAHMA FADHILA",
            "ALVINO VALERIAN DANISWARA RAHMAN",
            "ANANDA RAHMAWATI",
            "BILLY MAULANA FERDINAN",
            "FAHRI ZANUAR PRADIAN",
            "FAISHAL HARIST RAHMAWAN",
            "FALI IRHAM MAULANA",
            "HAMDAN AZIZUL HAKIM",
            "HANIFAH KURNIASARI",
            "HIKMAH ALDRIN ABDILLAH",
            "KEISYA NISRINA AULIA",
            "LUQMAN ANANTA ABDUL HAKIM",
            "LUTHFIYYAH ADZKA NUR SHABRINA",
            "MUHAMMAD ADITYO RAHMAN",
            "MUHAMMAD NAUFAL PRATOMO",
            "MUHAMMAD SYAFIQ ALDIANSYAH",
            "NURWAHIB ZAKKI YAHYA",
            "OKTAVIAN EKA RAMADHAN",
            "RAYHAN HERU ARIFIANSYAH",
            "SAKA NABIL",
            "SATRIO WISNU ADI PRATAMA",
            "TOMI MARTINO AFFANDI",
            "VIRA ALFITA YUNIA",
            "WAHYU RIZKY CAHYANA",
            "ADHAM BASKARA",
            "ADITYA ATADEWA",
            "AHMAD FADLIH WAHYU SARDANA",
            "AKHMAD AAKHIF ATHALLAH",
            "ALEXANDER AGUNG RAYA",
            "ANUGERAH RACHMADANI SUKMA HERIANTO",
            "AYLEEN RUHUL QISTHY",
            "DANENDRA ADHIPRAMANA",
            "DANENDRA NAYAKA PASSADHI",
            "DINA RAHMAWATI",
            "DUTA KURNIA ARDHANI",
            "FAIS RESTU PRATAMA",
            "FAJRUL SANTOSO",
            "FATIKAH SALSABILLA",
            "FAWWAZ ALIFIO FARSA",
            "FIERA ZIADATTUN NISA'",
            "GHAISAN RAFA PRADIPTA",
            "HAIKAL MUHAMMAD RAFLI",
            "IRSA CAHAYA WIDODO",
            "IVANSYAH EKA OKTAVIADI SANTOSO",
            "KEVIN ADIKA SAPUTRA",
            "KHOIROTUN NISA'",
            "MARSYA AURELIA SEFIRA",
            "MAULANA RENGGA RAMADAN",
            "MUHAMMAD AL-FATIH ULIMA ROBBY",
            "MUHAMMAD DHIA RAMADHANIL HAQ",
            "MUHAMMAD ERRIL PUTRA PRATIDINA",
            "NABEEL NIZAM",
            "NATHANAEL JUAN GRACEDO",
            "RAFI ABIYYU AIRLANGGA",
            "AGNA PUTRA PRAWIRA",
            "AHMAD ADZIN BRILLIAN LAZUARDY KARIM",
            "ANTONIUS KAHARAP KAUTSAR",
            "AQILLA APRILY KURNIA SARI",
            "BASKORO SENO AJI",
            "BAYU PUTRA LAKSMANA",
            "CHARELLINO KALINGGA SADEWO",
            "ERWAN MAJID",
            "FAHREIZA TAURA MUHAMMADANI",
            "FEBRIAN ARKA SAMUDRA",
            "GOLDEN CHRISTIAN GONDO",
            "HAMMAM ABDULLAH SAEED BIN GHALEB",
            "KEVIN BRAMASTA ARVYTO WARDHANA",
            "KHEN MUHAMMAD CAHYO",
            "KRISNA PRAWIRA NUGRAHA",
            "MIKAILA KAFKA AKMALSYAH",
            "MUHAMMAD ATHO'ILLAH MU'THISYAH",
            "MUHAMMAD FARHAN FAHRABY",
            "MUHAMMAD KHOIRUL ANWARUDIN",
            "MUHAMMAD RIZAL AL BAIHAQI",
            "MUHAMMAD TEGAR HIBATULLOH",
            "RIDHO ANFA'AL",
            "SHERLY LUTFI AZKIAH SULISTYAWATI",
            "XAVIER ZAIDANE ATHAYA",
            "YUMA AKHUNZA KAUSAR PUTRA"
        ];

        $kelamin = [
            'L',
            'L',
            'P',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'P',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'P',
            'L',
            'P',
            'P',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'P',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'L',
            'P',
            'L',
            'L',
        ];

        $jalan = ['Mawar', 'Melati', 'Kenanga', 'Flamboyan', 'Cendana', 'Delima', 'Kamboja', 'Bungur', 'Bougenville', 'Teratai'];

        // Ambil user Mahasiswa dari t_users mulai index 87 (user_id 88)
        $users = DB::table('t_users')
            ->orderBy('user_id')
            ->skip(87)  // Lewati 87 user pertama (index 0-86)
            ->take(count($names)) // Ambil sesuai banyaknya nama mahasiswa
            ->get()
            ->values();

        // Insert mahasiswa berdasarkan data users dan nama, kelamin
        foreach ($users as $index => $user) {
            DB::table('t_mahasiswa')->insert([
                'user_id' => $user->user_id,
                'prodi_id' => 1,
                'periode_id' => 1,
                'level_minbak_id' => rand(1, 4),
                'nim_mahasiswa' => $user->username, // Nim Sesuai Username
                'nama_mahasiswa' => isset($names[$index]) ? ucwords(strtolower($names[$index])) : 'Nama Tidak Diketahui',
                'angkatan' => '2023',
                'img_mahasiswa' => 'profil-default.png',
                'email' => null,
                'no_hp' => null,
                'alamat' => null,
                'kelamin' => $kelamin[$index] ?? 'Kelamin Tidak Diketahui',
            ]);
        }

        // Update email, no_hp, alamat mahasiswa
        $mahasiswa = DB::table('t_mahasiswa')
            ->where('angkatan', '2023')
            ->where('prodi_id', 1)
            ->get();

        foreach ($mahasiswa as $mhs) {
            DB::table('t_mahasiswa')
                ->where('mahasiswa_id', $mhs->mahasiswa_id)
                ->update([
                    'email' => 'mahasiswa' . $mhs->mahasiswa_id . '@example.com',
                    'no_hp' => '08' . str_pad(rand(0, 999999999), 9, '0', STR_PAD_LEFT),
                    'alamat' => 'Jl. ' . $jalan[array_rand($jalan)] . ' No. ' . rand(1, 15),
                ]);
        }
    }
}

